### ISSUE TITLE
Add memory caching (Reddis?) for improved performance

### ISSUE THREAD

**Issue by QEDeD** [spantaleev/nextcloud-docker-ansible-deploy#12]
Would you consider adding memory caching of some sort? According to Nextcloud's own documentation, this "...  can significantly improve your Nextcloud server performance" :)

Reddis, APCu and Memcached are the supported options:
https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/caching_configuration.html

**Comment by spantaleev** [comment]
I think it's currently using APCu by default or something, which is even faster than Redis for a single server setup (according to the Nextcloud docs). Redis only seems to be beneficial if you're running a clustered setup.

I may be wrong though..

**Comment by QEDeD** [comment]
Oh yes, you're right, they say "APCu is faster at local caching than Redis. If you have enough memory, use APCu for Memory Caching and Redis for File Locking. If you are low on memory, use Redis for both." - 
https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/caching_configuration.html#additional-notes-for-redis-vs-apcu-on-memory-caching

And they recommend just using APCu for a Small/Private home server -
https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/caching_configuration.html#small-private-home-server

Should done more thorough research :)
