### ISSUE TITLE
Add Collabora Installation and Integration

### ISSUE THREAD

**Issue by haghighi-ahmad** [spantaleev/nextcloud-docker-ansible-deploy#13]
Collabora has several advantages over OnlyOffice, specially for Multi-language usage.   
https://www.collaboraoffice.com/

**Comment by moan0s** [comment]
I did some work regarding that, feel free to check it out (but it is work in progress, so be careful): https://github.com/spantaleev/nextcloud-docker-ansible-deploy/pull/52

**Comment by moan0s** [comment]
Fixed/Implemented with 3f0d1b83ad1b8b714048f9372aadcdf37ff28a15

If you encounter any problems just let me know
