### ISSUE TITLE
php-imagick is missing

### ISSUE THREAD

**Issue by feydreva** [spantaleev/nextcloud-docker-ansible-deploy#23]
Hello, 
I installed a new instance today.
Nextcloud security and warning message : 

Module php-imagick in this instance has no SVG support. For better compatibility it is recommended to install it.

That has to do with nginx right ? how can we add it to the docker image of nginx ?

**Comment by spantaleev** [comment]
This has to do with the `nextcloud-apache` container (the [docker.io/nextcloud](https://hub.docker.com/_/nextcloud) container image).

If you think it's a bug with that container image, you can report it [upstream](https://github.com/nextcloud/docker/issues).

We just use images as-is, without modifying them ourselves.

**Comment by spantaleev** [comment]
Looks like an issue already exists here: https://github.com/nextcloud/docker/issues/1414
