### ISSUE TITLE
Onlyoffice configuration issue

### ISSUE THREAD

**Issue by feydreva** [spantaleev/nextcloud-docker-ansible-deploy#28]
Hello, 
I am having issue with only office.
when I try to open a document, I get the pop-up "documment cannot be saved" and the pop-up "Cannot download document"
It looks like it s a configuration issue between Only Office and next cloud.

I am not sure on how to fill the only office configuration tab in the nextcloud settings.

I have read the document in https://api.onlyoffice.com/editors/nextcloud, but I am still not sure on how to fill it.

I see the internal address for nextcloud and only office is: http://nextcloud-onlyoffice-document-server/
but is seem I need 2 differents adress ?

With this configuration, I get this error : 
"Error when trying to connect (Host violates local access rules)"

![image](https://user-images.githubusercontent.com/3083670/155886735-d37feac5-5902-44e0-97cd-920c3c5be57e.png)

thank you for you help.
Best Regards

**Comment by spantaleev** [comment]
Someone just upgraded our OnlyOffice package to v7.0 here - https://github.com/spantaleev/nextcloud-docker-ansible-deploy/pull/30

It seems like it works for them, so maybe your setup has some customizations which make it fail?

**Comment by feydreva** [comment]
Hello, after fiddleing around, it works.
I don't know what happeened before.
