### ISSUE TITLE
Disabling SSL Certificate retrieving

### ISSUE THREAD

**Issue by mxwmnn** [spantaleev/nextcloud-docker-ansible-deploy#37]
I'm using a nginx reverse proxy in front of the nextcloud server, so it would be nice to disable the ssl retrieving!

**Comment by spantaleev** [comment]
With `nextcloud_nginx_proxy_enabled: false`, you disable both the internal nginx server that we use and SSL certificate retrieving.

Sample nginx configuration (for use with your other nginx server) will still be made available in `/nextcloud/nginx-proxy/conf.d`.

**Comment by mxwmnn** [comment]
That's true, but i wanted to set it up like in your matrix playbook. To use still the nginx server but with no SSL retrieval. 
But thanks, will do a workaround here, with an external nginx webserver

**Comment by spantaleev** [comment]
You'd like to provide the SSL certificates manually, like with `matrix_ssl_retrieval_method: manually-managed`?

You'd then be mounting them into the container, etc.

**Comment by mxwmnn** [comment]
Not exactly. I use matrix_ssl_retrieval_method : none , cause the reverse proxy is serving the required certificates

**Comment by mxwmnn** [comment]
Ah sorry, saw that the apache server is running too, can set it up now was too fast reading the configs and to complain.

**Comment by mxwmnn** [comment]
Even with nginx proxy set to false he´s trying to get SSL certificates?

**Comment by spantaleev** [comment]
Since ed8f86ed8cc4196f983e, you should be able to disable SSL certificate retrieval using: `nextcloud_ssl_retrieval_method: none`
