### ISSUE TITLE
Local folder mount as external storage

### ISSUE THREAD

**Issue by tanc** [spantaleev/nextcloud-docker-ansible-deploy#4]
I'm interesting in mounting a local storage folder in Nextcloud using the external storage module. The only problem is that this would also have to be mounted in the docker container. Is there a setting to mount extra directories into the container?

**Comment by spantaleev** [comment]
If `nextcloud_goofys_external_storage_enabled` is set to `true`, `nextcloud_external_storage_path` would be mounted at the same location within the container.

.. but setting `nextcloud_goofys_external_storage_enabled` would do many other things to set up Goofys. It's probably not what you want.

-------

Alternatively:

`nextcloud_nextcloud_data_path` (defaults to `/nextcloud/nextcloud-data`) gets mounted at `/var/www/html`.

If you put some other directories inside `/nextcloud/nextcloud-data`, you should be able to access them from `/var/www/html/...`.

Mounting additional volumes is not currently supported, but we can probably add new variables to allow for this.

**Comment by tanc** [comment]
Thanks for the quick response. For my use I can't add the directories within `/nextcloud/nextcloud-data` as the directories are already in use elsewhere on the system and other containers have mounted them. So ideally I'd be able to add variables to choose one or more extra mounts that would get passed as volumes to the docker run command.

**Comment by spantaleev** [comment]
Isn't it feasible to do a bind mount to expose those same directories in a different place?
