### ISSUE TITLE
ARM64 Support?

### ISSUE THREAD

**Issue by OscarKevinXR** [spantaleev/nextcloud-docker-ansible-deploy#44]
Hi! I navigated here from the matrix deploy repo and really love the project! Question: is ARM64 usable with this project?

I see in this runbook that ARM32 works, so I was wondering if anything extra is needed to rig this for ARM64
https://github.com/spantaleev/nextcloud-docker-ansible-deploy/blob/master/roles/nextcloud-server/defaults/main.yml#L35-L43

**Comment by spantaleev** [comment]
This is about the `matrix_debian_arch` variable, which needs to be set to one of: `amd64`, `arm64` or `armhf` (when `nextcloud_architecture` is set to `arm32`).

To get Nextcloud running on arm64, just set `nextcloud_architecture: arm64`. It seems like the basic components should work, although I haven't tested it. If you hit some trouble, let us know or better yet, submit a PR!

**Comment by OscarKevinXR** [comment]
The basic workflow works except for the dependency on certbot because the image is only in amd64 -> https://hub.docker.com/r/certbot/certbot/tags. 

To remedy this, I had to change `nextcloud_ssl_retrieval_method` to `none` and am currently attempting to integrated this to my traefik config, I'll spin up a PR once I figure it out!

**Comment by spantaleev** [comment]
The Certbot problem was easy to fix. Done in e215dde.

You can consider removing `nextcloud_ssl_retrieval_method: none` and sticking to the `nginx` proxy provided with the playbook.
