### ISSUE TITLE
Error "Before installing and making use of the OnlyOffice app, you need to install the OnlyOffice services (see `nextcloud_onlyoffice_document_server_enabled`)"

### ISSUE THREAD

**Issue by ni-ka** [spantaleev/nextcloud-docker-ansible-deploy#54]
I'm trying to install onlyoffice server, and have added this line to inventory/host_vars/hostname:
`nextcloud_onlyoffice_document_server_enabled: true`

i get the following error:
```
ansible-playbook -i inventory/hosts setup.yml --tags=setup-onlyoffice-app

--- SNAP---

TASK [custom/nextcloud_onlyoffice_document_server : Fail if OnlyOffice not enabled] ********************
fatal: [host]: FAILED! => {"changed": false, "msg": "Before installing and making use of the OnlyOffice app, you need to install the OnlyOffice services (see `nextcloud_onlyoffice_document_server_enabled`)"}
```

**Comment by moan0s** [comment]
AFAIK the OnlyOffice integration works with two components: 
- The document server which does provide most of the infrastructure
- The app which integrates the server into nextcloud

For a working integration you need both. First the server, then the app. So you should follow the advice the error message gives you and also set `nextcloud_onlyoffice_document_server_enabled: true`.

All of this you can find in the [docs](https://github.com/spantaleev/nextcloud-docker-ansible-deploy/blob/master/docs/configuring-playbook-onlyoffice.md).

**Warning:** The OnlyOffice server install is currently broken (I don't know the exact issue). It probably needs fixing. If you want a ready to use solution you might want do go with the [collabora role](https://github.com/spantaleev/nextcloud-docker-ansible-deploy/blob/master/docs/configuring-playbook-collabora-online.md)

**Comment by ni-ka** [comment]
Thanks @moan0s for the infos, I did submit the bug report  _because_ I had added the variable and am still getting the error.

**Comment by moan0s** [comment]
Sorry, did not read that correctly.

I tried to recreate that on my tesbed but could not reproduce the error. For reference: Here is my `vars.yml`

```
# This is your Nextcloud server's domain name.
#
# Example value: nextcloud.example.com
nextcloud_server_fqn_nextcloud: cloud.mydomain.org

# A secret used as a base, for generating various other secrets.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
nextcloud_generic_secret_key: 'secret'

# A Postgres password to use for the superuser Postgres user (called `root` by default).
#
# The playbook creates additional Postgres users and databases (one for each enabled service) using this superuser account.
devture_postgres_connection_password: 'secret'

# A Postgres password to use for the `nextcloud` database.
# You will use the same password during initial Nextcloud installation.
nextcloud_nextcloud_database_password: 'secret'
devture_traefik_ssl_email_address: 'cert@hyteck.de'

nextcloud_onlyoffice_document_server_enabled: true
```

**Comment by spantaleev** [comment]
This playbook is [no longer supported](https://github.com/spantaleev/nextcloud-docker-ansible-deploy/blob/master/CHANGELOG.md#this-playbook-has-been-absorbed-into-the-mash-playbook), so this issue is no longer relevant. The Nextcloud offering part of mash-playbook does not support OnlyOffice integration (yet), so it's not relevant there either.
