### ISSUE TITLE
[feature] Backups

### ISSUE THREAD

**Issue by moan0s** [spantaleev/nextcloud-docker-ansible-deploy#55]
The playbook currently does not support automated backups. We could implement something borg-based like in [matrix-docker-ansible-deploy](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-backup-borg.md)

**Comment by spantaleev** [comment]
We should probably get that matrix borg backup role decoupled from the Matrix playbook.. Once it's reusable, it could be plugged here.

**Comment by moan0s** [comment]
Yes. I just started working on it and it seems to be Copy-Paste-Replace so far. Should I try to decouple or is a custom role here nevertheless a good start?

**Comment by spantaleev** [comment]
A custom role here means we'll need to maintain it like this forever.. Or untangle it again later.

Ideally, we'd decouple and make it reusable first, and then add it here. Being able to serve both playbooks is a good way to ensure the extracted-out role is done well enough.

**Comment by moan0s** [comment]
Yes, probably true.
I started it nevertheless: https://github.com/moan0s/nextcloud-docker-ansible-deploy

But I'll continue with a decoupled role.

**Comment by moan0s** [comment]
Start of a decoupled role: https://github.com/moan0s/ansible.role.backup_borg

**Comment by spantaleev** [comment]
With minor improvements, this role was published here: https://gitlab.com/etke.cc/roles/backup_borg

Now, we need to integrate it into this Nextcloud playbook.
